//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 04:58:42 PM CET 
//


package eu.fbk.das.annotation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.das.annotation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Annotations_QNAME = new QName("http://das.fbk.eu/Annotation", "annotations");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.das.annotation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClauseType }
     * 
     */
    public ClauseType createClauseType() {
        return new ClauseType();
    }

    /**
     * Create an instance of {@link ClauseType.Point }
     * 
     */
    public ClauseType.Point createClauseTypePoint() {
        return new ClauseType.Point();
    }

    /**
     * Create an instance of {@link EffectType }
     * 
     */
    public EffectType createEffectType() {
        return new EffectType();
    }

    /**
     * Create an instance of {@link AnnotationListType }
     * 
     */
    public AnnotationListType createAnnotationListType() {
        return new AnnotationListType();
    }

    /**
     * Create an instance of {@link PreconditionType }
     * 
     */
    public PreconditionType createPreconditionType() {
        return new PreconditionType();
    }

    /**
     * Create an instance of {@link GoalType }
     * 
     */
    public GoalType createGoalType() {
        return new GoalType();
    }

    /**
     * Create an instance of {@link CompensationType }
     * 
     */
    public CompensationType createCompensationType() {
        return new CompensationType();
    }

    /**
     * Create an instance of {@link ClauseType.Point.DomainProperty }
     * 
     */
    public ClauseType.Point.DomainProperty createClauseTypePointDomainProperty() {
        return new ClauseType.Point.DomainProperty();
    }

    /**
     * Create an instance of {@link EffectType.Event }
     * 
     */
    public EffectType.Event createEffectTypeEvent() {
        return new EffectType.Event();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://das.fbk.eu/Annotation", name = "annotations")
    public JAXBElement<AnnotationListType> createAnnotations(AnnotationListType value) {
        return new JAXBElement<AnnotationListType>(_Annotations_QNAME, AnnotationListType.class, null, value);
    }

}
