//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 04:58:42 PM CET 
//


package eu.fbk.das.domainobject;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.das.domainobject package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.das.domainobject
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DomainObject }
     * 
     */
    public DomainObject createDomainObject() {
        return new DomainObject();
    }

    /**
     * Create an instance of {@link DomainObject.DomainKnowledge }
     * 
     */
    public DomainObject.DomainKnowledge createDomainObjectDomainKnowledge() {
        return new DomainObject.DomainKnowledge();
    }

    /**
     * Create an instance of {@link DomainObject.State }
     * 
     */
    public DomainObject.State createDomainObjectState() {
        return new DomainObject.State();
    }

    /**
     * Create an instance of {@link DomainObject.Process }
     * 
     */
    public DomainObject.Process createDomainObjectProcess() {
        return new DomainObject.Process();
    }

    /**
     * Create an instance of {@link DomainObject.Fragment }
     * 
     */
    public DomainObject.Fragment createDomainObjectFragment() {
        return new DomainObject.Fragment();
    }

    /**
     * Create an instance of {@link DomainObject.DomainKnowledge.InternalDomainProperty }
     * 
     */
    public DomainObject.DomainKnowledge.InternalDomainProperty createDomainObjectDomainKnowledgeInternalDomainProperty() {
        return new DomainObject.DomainKnowledge.InternalDomainProperty();
    }

    /**
     * Create an instance of {@link DomainObject.DomainKnowledge.ExternalDomainProperty }
     * 
     */
    public DomainObject.DomainKnowledge.ExternalDomainProperty createDomainObjectDomainKnowledgeExternalDomainProperty() {
        return new DomainObject.DomainKnowledge.ExternalDomainProperty();
    }

}
