//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 04:58:42 PM CET 
//


package eu.fbk.das.fragment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.das.fragment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.das.fragment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fragment }
     * 
     */
    public Fragment createFragment() {
        return new Fragment();
    }

    /**
     * Create an instance of {@link Fragment.Transition }
     * 
     */
    public Fragment.Transition createFragmentTransition() {
        return new Fragment.Transition();
    }

    /**
     * Create an instance of {@link Fragment.State }
     * 
     */
    public Fragment.State createFragmentState() {
        return new Fragment.State();
    }

    /**
     * Create an instance of {@link Fragment.Action }
     * 
     */
    public Fragment.Action createFragmentAction() {
        return new Fragment.Action();
    }

    /**
     * Create an instance of {@link ServiceActionType }
     * 
     */
    public ServiceActionType createServiceActionType() {
        return new ServiceActionType();
    }

    /**
     * Create an instance of {@link ServiceStateType }
     * 
     */
    public ServiceStateType createServiceStateType() {
        return new ServiceStateType();
    }

    /**
     * Create an instance of {@link Fragment.Transition.Action }
     * 
     */
    public Fragment.Transition.Action createFragmentTransitionAction() {
        return new Fragment.Transition.Action();
    }

}
